### ISSUE TITLE
[Question] implementation of Magento quotes with Mongo

### ISSUE THREAD

**Issue by yatsyukv** [colinmollenhour/magento-mongo#18]
Hi, Colin.

I'm very excited with work you've done on implementing this abstraction layer for MongoDB - it's awesome.

I've got more like general question for you. Probably, while implementing this extension you was thinking about possible use cases where MongoDB usage can make things work better, so:

Currently I'm working with a pretty high-load Magento store, and while thinking about possible optimizations I had a thought about rewriting all of the quote_* related stuff to use MongoDB as read\write resource. My initial assumption is that all of the quote related tables are very insert\read\update intensive and placing all of that information into a single Mongo Document can make things much more efficient.

As you probably know - doing that task is definitely not a piece of cake and require really massive Magento override and a bunch of time, so before actually doing this I want to ask you for an advice.

* Do you feel that this approach will really be a performance optimization, or i'm thinking in a wrong direction?
* Do you have such an experience? I mean - making Magento quotes utilize MongoDB. Was it successful in terms of performance? 
* What issues would you expect with this solution?
* Is this game worth of candles? I mean - if you had such a problem would you go with this approach at all?

Sorry for such a weird questions, but everything above is not kind of typical problem, and I can't think about a better candidate to ask these except of you.

Thanks for your time and your answers.

**Comment by MatGiaimo** [comment]
Hi Colin-

I also share Seva's excitement about the work you have done with MongoDB and Magento.  I am exploring options to migrate the Magento catalog to a NoSQL storage solution.

Seva has some great questions... you're thoughts on the topic would be greatly appreciated.

Thanks for your time and for your contributions to the Magento community.

**Comment by colinmollenhour** [comment]
> Do you feel that this approach will really be a performance optimization, or i'm thinking in a wrong direction?

MySQL is an extremely well optimized database and I personally have not found that the quotes_* tables suffer from anything that I think MongoDb can fix. Sure, you could condense a handful of row operations into a Mongo document but I don't know that the end result would be faster and you will undoubtedly lose some much needed functionality. Also there is the whole transactional bit..

> Do you have such an experience? I mean - making Magento quotes utilize MongoDB. Was it successful in terms of performance?

The closest experience I have is using this plugin for a system that would create invoices for services (did not use products but rather a custom entity) and charge credit cards. The lack of ACID compliance made it extremely difficult and in the end I wish I had just used MySQL.

> What issues would you expect with this solution?

Lack of transactions makes it really hard to keep consistent data. Loss of flexibility of using joins with product tables, etc.

> Is this game worth of candles? I mean - if you had such a problem would you go with this approach at all?

I don't know exactly what your problem is, but I would only switch away from MySQL in favor of MongoDb if my problem fit MongoDb *extremely* well and none of MongoDb's weaknesses would be an issue at all. I don't know offhand any areas in Magento where this is the case except perhaps for the Cache (I have already done this and it works well, code available on github).

One feature of Magento is to have multiple database connections, so if you are experiencing bottlenecks with the database one option might be to move some tables to a separate server and use the config.xml to tell Magento which connection to use for which resources. However, orders and quotes will need to stick together for sure and if there are any joins or transactions that span both connections then this may be a no-go. For example, it might be safe to move all report_*, log_*, etc.
